import catalog from "@/content/activity-catalog.json"
import { makeMatcher, type Matcher } from "@/lib/activity/sanitize"

/** content/activity-catalog.json, typed. Regenerated by `npm run activity:scan`, which also runs in prebuild. */
export type CatalogControl = { id: string; label: string | null; file: string }
export type Catalog = {
  routes: string[]
  controls: CatalogControl[]
  actions: { total: number; wrapped: number; files: { file: string; total: number; wrapped: number }[] }
}

export const CATALOG = catalog as Catalog

let matcher: Matcher | null = null

export function routeMatcher(): Matcher {
  if (!matcher) matcher = makeMatcher(CATALOG.routes)
  return matcher
}
