import { and, desc, eq } from "drizzle-orm"
import { db } from "@/db"
import { codebaseDocs, clients, products, projects, sites } from "@/db/schema"
import type { CodebaseDoc } from "@/db/schema"

/**
 * Codebase documents — sheets a tool generated by reading a codebase. The
 * latest row per (client, codebase, kind) is the current sheet; older rows are
 * the history a rerun leaves behind.
 */

export const DOC_KINDS = ["spec", "structure", "db", "features", "permissions"] as const
export type DocKind = (typeof DOC_KINDS)[number]

export const DOC_KIND_LABEL: Record<DocKind, string> = {
  spec: "Spec sheet",
  structure: "Folder structure",
  db: "Database",
  features: "Features",
  permissions: "Permissions",
}

/** Latest doc of every kind for every codebase of a client. */
export async function latestDocsFor(clientId: string): Promise<CodebaseDoc[]> {
  const rows = await db.query.codebaseDocs.findMany({
    where: eq(codebaseDocs.clientId, clientId),
    orderBy: [desc(codebaseDocs.generatedAt)],
  })
  const seen = new Set<string>()
  const latest: CodebaseDoc[] = []
  for (const row of rows) {
    const key = `${row.codebase}:${row.kind}`
    if (seen.has(key)) continue
    seen.add(key)
    latest.push(row)
  }
  return latest.sort((a, b) => a.codebase.localeCompare(b.codebase) || a.kind.localeCompare(b.kind))
}

export async function latestDoc(clientId: string, codebase: string, kind: string) {
  return db.query.codebaseDocs.findFirst({
    where: and(
      eq(codebaseDocs.clientId, clientId),
      eq(codebaseDocs.codebase, codebase),
      eq(codebaseDocs.kind, kind)
    ),
    orderBy: [desc(codebaseDocs.generatedAt)],
  })
}

export async function docHistory(clientId: string, codebase: string, kind: string, limit = 12) {
  return db.query.codebaseDocs.findMany({
    where: and(
      eq(codebaseDocs.clientId, clientId),
      eq(codebaseDocs.codebase, codebase),
      eq(codebaseDocs.kind, kind)
    ),
    orderBy: [desc(codebaseDocs.generatedAt)],
    columns: { id: true, generatedAt: true, commitHash: true, branch: true, summary: true, tool: true },
    limit,
  })
}

export type StoreDocInput = {
  clientSlug: string
  codebase: string
  kind: string
  schemaVersion: number
  title: string
  summary: string
  data: Record<string, unknown>
  commitHash: string
  branch: string
  tool: string
  sourcePath: string
  generatedAt: Date
  siteSlug?: string | null
  projectSlug?: string | null
  productSlug?: string | null
}

export type StoreDocResult =
  | { ok: true; id: string; replayed: boolean; clientId: string }
  | { ok: false; status: number; error: string }

const SLUG = /^[a-z0-9][a-z0-9._-]{0,80}$/

function stableJson(value: unknown): string {
  return JSON.stringify(value, (_k, v) =>
    v && typeof v === "object" && !Array.isArray(v)
      ? Object.fromEntries(Object.entries(v as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)))
      : v
  )
}

/**
 * Store a generated sheet. A rerun that read the same commit and produced the
 * same data is a no-op — the existing row comes back with `replayed: true` —
 * so "run it again after every change" never piles up identical rows.
 */
export async function storeCodebaseDoc(input: StoreDocInput): Promise<StoreDocResult> {
  const codebase = input.codebase.trim().toLowerCase()
  if (!SLUG.test(codebase)) return { ok: false, status: 400, error: "codebase must be a slug (a-z, 0-9, . _ -)." }
  if (!(DOC_KINDS as readonly string[]).includes(input.kind)) {
    return { ok: false, status: 400, error: `kind must be one of ${DOC_KINDS.join(", ")}.` }
  }
  if (!input.data || typeof input.data !== "object") return { ok: false, status: 400, error: "data must be an object." }
  if (Number.isNaN(input.generatedAt.getTime())) return { ok: false, status: 400, error: "generatedAt must be an ISO timestamp." }

  const client = await db.query.clients.findFirst({ where: eq(clients.slug, input.clientSlug) })
  if (!client) return { ok: false, status: 404, error: `No client with slug "${input.clientSlug}".` }

  let siteId: string | null = null
  if (input.siteSlug) {
    const site = await db.query.sites.findFirst({ where: eq(sites.slug, input.siteSlug) })
    if (!site) return { ok: false, status: 404, error: `No site with slug "${input.siteSlug}".` }
    siteId = site.id
  }
  let projectId: string | null = null
  if (input.projectSlug) {
    const project = await db.query.projects.findFirst({ where: eq(projects.slug, input.projectSlug) })
    if (!project) return { ok: false, status: 404, error: `No project with slug "${input.projectSlug}".` }
    if (project.clientId !== client.id) return { ok: false, status: 400, error: "That project belongs to another client." }
    projectId = project.id
  }
  let productId: string | null = null
  if (input.productSlug) {
    const product = await db.query.products.findFirst({ where: eq(products.slug, input.productSlug) })
    if (!product) return { ok: false, status: 404, error: `No product with slug "${input.productSlug}".` }
    productId = product.id
  }

  const previous = await latestDoc(client.id, codebase, input.kind)
  if (
    previous &&
    previous.commitHash === input.commitHash &&
    stableJson(previous.data) === stableJson(input.data)
  ) {
    return { ok: true, id: previous.id, replayed: true, clientId: client.id }
  }

  const [row] = await db
    .insert(codebaseDocs)
    .values({
      clientId: client.id,
      siteId,
      projectId,
      productId,
      codebase,
      kind: input.kind,
      schemaVersion: input.schemaVersion,
      title: input.title.trim().slice(0, 200),
      summary: input.summary.trim().slice(0, 300),
      data: input.data,
      commitHash: input.commitHash.trim().slice(0, 64),
      branch: input.branch.trim().slice(0, 120),
      tool: input.tool.trim().slice(0, 80),
      sourcePath: input.sourcePath.trim().slice(0, 400),
      generatedAt: input.generatedAt,
    })
    .returning({ id: codebaseDocs.id })
  return { ok: true, id: row.id, replayed: false, clientId: client.id }
}
