import type { LucideIcon } from "lucide-react"
import {
  Activity,
  BarChart3,
  Building2,
  Calendar,
  CheckSquare,
  Clock,
  ClipboardCheck,
  ClipboardList,
  Rows3,
  Smartphone,
  Table2,
  FileSignature,
  FileText,
  FolderKanban,
  Inbox,
  Kanban,
  LayoutDashboard,
  LineChart,
  Megaphone,
  Mail,
  Plug,
  Receipt,
  Repeat,
  Route,
  Target,
  TrendingUp,
  Settings,
  UserCog,
  Users,
  Wallet,
  LifeBuoy,
  MonitorCheck,
  NotebookText,
  Package,
  KeyRound,
  ScrollText,
} from "lucide-react"
import type { NavIconName } from "@/lib/nav"

const ICONS: Record<NavIconName, LucideIcon> = {
  dashboard: LayoutDashboard,
  inbox: Inbox,
  pipeline: Kanban,
  delivery: Rows3,
  contacts: Users,
  clients: Building2,
  projects: FolderKanban,
  retainers: Repeat,
  leads: Target,
  calendar: Calendar,
  tasks: CheckSquare,
  activity: Activity,
  emails: Mail,
  proposals: FileText,
  worksheets: ClipboardList,
  contracts: FileSignature,
  invoices: Receipt,
  expenses: Wallet,
  timesheet: Clock,
  clock: Clock,
  review: ClipboardCheck,
  sheets: Table2,
  ledger: Rows3,
  devices: Smartphone,
  attribution: Route,
  analytics: LineChart,
  ads: Megaphone,
  reports: BarChart3,
  revenue: TrendingUp,
  logs: ScrollText,
  support: LifeBuoy,
  uptime: MonitorCheck,
  notebooks: NotebookText,
  vault: KeyRound,
  product: Package,
  settings: Settings,
  team: UserCog,
  "email-settings": Mail,
  integrations: Plug,
}

export function navIcon(name: NavIconName): LucideIcon {
  return ICONS[name]
}
