/**
 * The activity catalog: what exists in the code, so /activity can show what
 * was never used — a count can only be zero against a list.
 *
 *   routes    every page.tsx under app/, as a route pattern (route groups dropped)
 *   controls  every data-track="…" id, with its data-track-label when one is set
 *   actions   exported server actions per "use server" file, and how many are
 *             wrapped in tracked()
 *
 * Writes content/activity-catalog.json. Pure fs, no database — it runs in
 * prebuild, so a deploy always carries its own routes. It never fails a
 * build: an unreadable file is skipped and named.
 *
 *   npm run activity:scan
 */
import { existsSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs"
import { join, relative, sep } from "node:path"

const ROOT = process.cwd()
const OUT = join(ROOT, "content", "activity-catalog.json")
const skipped: string[] = []

function walk(dir: string, match: (name: string) => boolean, out: string[] = []): string[] {
  if (!existsSync(dir)) return out
  for (const name of readdirSync(dir)) {
    if (name === "node_modules" || name.startsWith(".next")) continue
    const p = join(dir, name)
    let isDir = false
    try {
      isDir = statSync(p).isDirectory()
    } catch {
      skipped.push(relative(ROOT, p))
      continue
    }
    if (isDir) walk(p, match, out)
    else if (match(name)) out.push(p)
  }
  return out
}

function read(file: string): string {
  try {
    return readFileSync(file, "utf8")
  } catch {
    skipped.push(relative(ROOT, file))
    return ""
  }
}

/* ------------------------------------------------------------------ routes */
const routes = new Set<string>()
for (const file of walk(join(ROOT, "app"), (n) => /^page\.(tsx|ts|jsx|js)$/.test(n))) {
  const segs = relative(join(ROOT, "app"), file).split(sep).slice(0, -1)
  if (segs.some((s) => s.startsWith("_") || s.startsWith("@") || s.startsWith("(."))) continue
  const kept = segs.filter((s) => !(s.startsWith("(") && s.endsWith(")")))
  routes.add("/" + kept.join("/"))
}

/* ---------------------------------------------------------------- controls */
type Control = { id: string; label: string | null; file: string }
const controls = new Map<string, Control>()
const TRACK = /data-track=(?:"([^"]+)"|\{\s*"([^"]+)"\s*\}|\{\s*`([^`]+)`\s*\})/g
for (const file of walk(join(ROOT, "app"), (n) => /\.(tsx|jsx)$/.test(n)).concat(walk(join(ROOT, "components"), (n) => /\.(tsx|jsx)$/.test(n)))) {
  const src = read(file)
  if (!src.includes("data-track=")) continue
  let m: RegExpExecArray | null
  TRACK.lastIndex = 0
  while ((m = TRACK.exec(src))) {
    const id = (m[1] ?? m[2] ?? m[3] ?? "").replace(/\$\{[^}]*\}/g, "*").trim()
    if (!id) continue
    const tagEnd = src.indexOf(">", m.index)
    const tag = src.slice(m.index, tagEnd === -1 ? m.index + 400 : tagEnd)
    const label = /data-track-label="([^"]+)"/.exec(tag)?.[1] ?? null
    const existing = controls.get(id)
    if (!existing || (!existing.label && label)) controls.set(id, { id, label, file: relative(ROOT, file) })
  }
}

/* ----------------------------------------------------------------- actions */
type ActionFile = { file: string; total: number; wrapped: number }
const actionFiles: ActionFile[] = []
for (const file of walk(join(ROOT, "app"), (n) => /\.(ts|tsx)$/.test(n)).concat(walk(join(ROOT, "lib"), (n) => /\.(ts|tsx)$/.test(n)))) {
  const src = read(file)
  const head = src.replace(/^\s*(\/\/[^\n]*\n|\/\*[\s\S]*?\*\/\s*)*/, "").trimStart()
  if (!head.startsWith('"use server"') && !head.startsWith("'use server'")) continue
  const plain = (src.match(/^export async function \w+/gm) ?? []).length
  const wrapped = (src.match(/^export const \w+\s*=\s*tracked\(/gm) ?? []).length
  if (plain + wrapped) actionFiles.push({ file: relative(ROOT, file), total: plain + wrapped, wrapped })
}
actionFiles.sort((a, b) => a.file.localeCompare(b.file))

const catalog = {
  note: "Generated by npm run activity:scan (also runs in prebuild). Do not edit by hand.",
  routes: Array.from(routes).sort(),
  controls: Array.from(controls.values()).sort((a, b) => a.id.localeCompare(b.id)),
  actions: {
    total: actionFiles.reduce((n, f) => n + f.total, 0),
    wrapped: actionFiles.reduce((n, f) => n + f.wrapped, 0),
    files: actionFiles,
  },
}

const next = JSON.stringify(catalog, null, 2) + "\n"
const previous = existsSync(OUT) ? readFileSync(OUT, "utf8") : ""
if (next !== previous) writeFileSync(OUT, next)
console.log(
  `activity catalog: ${catalog.routes.length} routes · ${catalog.controls.length} controls · ` +
    `${catalog.actions.wrapped} of ${catalog.actions.total} actions wrapped${next === previous ? " (unchanged)" : ""}`
)
if (skipped.length) console.log(`skipped (unreadable): ${skipped.join(", ")}`)
